// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACRVLQeUVNflozKWvtoomtDlOfnTxtM2g',
    appId: '1:108011034403:android:dbba129a79237b86361e96',
    messagingSenderId: '108011034403',
    projectId: 'periodiconaranja-74484',
    databaseURL: 'https://periodiconaranja-74484-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'periodiconaranja-74484.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1bc57c9aWvJv61cCvUWKt4jFuS9IaqfE',
    appId: '1:108011034403:web:627dadecd8eaee83361e96',
    messagingSenderId: '108011034403',
    projectId: 'periodiconaranja-74484',
    authDomain: 'periodiconaranja-74484.firebaseapp.com',
    databaseURL: 'https://periodiconaranja-74484-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'periodiconaranja-74484.firebasestorage.app',
    measurementId: 'G-ZBSFE52PDJ',
  );
}
